version: '3.8'

services:
  api:
    build: .
    container_name: scraper_api
    command: python main.py api
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    # Environment variables for FastAPI (optional, but good practice)
    environment:
      - PYTHONUNBUFFERED=1 # Ensure Python output is unbuffered
      - LOG_LEVEL=info

  cli:
    build: .
    container_name: scraper_cli
    command: python main.py cli
    depends_on:
      - mongo
    tty: true
    stdin_open: true

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: